### PR TITLE
 [SDK-160]: Added saving of image to Django example project

### PR DESCRIPTION
**Pull request by echarrod**

### CODE REVIEW

**Comment by vassyz** [comment]
@echarrod I added a few tweaks to the Flask example. Would it be possible to add the `dotenv` feature to the Django example as well? Possibly also mentioning the `.env` file in the Running the examples section. Does Django add the static folder itself? It doesn't seem to be added to this pull request.

**Comment by echarrod** [comment]
I should have separated this out into separate PRs, apologies

**Comment by echarrod** [comment]
I've created a separate branch for the removal of the old buttons etc., so I won't add anything else to this PR

**Comment by vassyz** [comment]
@echarrod Is it possible to add the dotenv plugin to Django, similar to how Flask works?

**Comment by echarrod** [comment]
Yes sorry, it was on my TODO list. Added it in the last commit, and I removed all my environment variables set through my IDE to check it works.

**Comment by vassyz** [comment]
@echarrod One las thing, can you also copy the `.env.example` file over from the Flask example? 😄

**Pull request merged**
